version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    volumes: [db_data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD","pg_isready","-U","demo"]
      interval: 5s
      retries: 5
    ports: ["5432:5432"]

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://demo:demo@db:5432/demo
      FLASK_ENV: development
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]
    command:
      - gunicorn
      - -k
      - gevent
      - -b
      - 0.0.0.0:8000
      - backend.app:create_app()
      - --reload

volumes:
  db_data:
